name: stripe_sdk
description: The only native Stripe library for Flutter. Has complete support for SCA/PSD2, payment intents and the newest Stripe features.
version: 2.7.0
homepage: https://github.com/ezet/stripe_sdk

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+4
  url_launcher: ^5.4.2
  uni_links: ^0.2.0
  mask_text_input_formatter: ^1.0.6
  awesome_card: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
